"""missing columns

Revision ID: 4c03c61f8cf6
Revises: a93a6d3989ba
Create Date: 2025-07-28 21:39:47.525773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c03c61f8cf6'
down_revision: Union[str, Sequence[str], None] = 'a93a6d3989ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('concept', sa.Text(), nullable=False))
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('expenses_types', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('expenses_types', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.drop_column('expenses_types', 'updated_at')
    op.drop_column('expenses_types', 'created_at')
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'created_at')
    op.drop_column('expenses', 'expense_date')
    op.drop_column('expenses', 'concept')
    # ### end Alembic commands ###
