"""fix_amount_length

Revision ID: 62b923d43715
Revises: 4c03c61f8cf6
Create Date: 2025-08-30 19:52:10.362322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b923d43715'
down_revision: Union[str, Sequence[str], None] = '4c03c61f8cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'saving',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'saving',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
